language: cpp
compiler:
- clang
- gcc
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- sudo apt-get install libosmesa6-dev
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script: ./tests/run-tests.sh
after_success:
- sudo apt-get --no-install-recommends install doxygen
- git clone https://github.com/iauns/travis-doxy-helper ./doxy-helper
- ./doxy-helper/update-doxygen.sh ./.dox ./dox-repo https://github.com/iauns/cpm-arc-ball
branches:
  only:
  - master
env:
  global:
    secure: TwnNQZOxLS7BM+vABBNsrS+yg4+Fn8oC7ZAVhQtxnk9o4Nvt/IDHLVJlbCBcauQRPtE/NogGO+KosU5BreH6qs4XX+1RTj1eTkoSCz1bMVHwKdROTBAbK1pqFTiO5ZAApsF8hw5jKAokSpboSQHkAS+ZgVH5mFCRoFDnBaT0t+k=
